name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if you are using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the appropriate Node.js version

    - name: Install dependencies
      run: npm install  # Adjust if you are using a different package manager

    - name: Build the site
      run: npm run build  # Adjust if you are using a different build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust to your build output directory
